name: "Xcel iTron MQTT - edge2"
description: "Bridge from Xcel iTron smart meters to MQTT - edge version"
url: "https://www.github.com/Teagan42/hassio-xcel-itron-mqtt"
version: "1.7.22"
slug: "xcel-itron-mqtt-edge2"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
services:
  - mqtt:need
panel_icon: mdi:meter-electric-outline
map:
  - addon_config:rw
options:
  meters: []
  cert_dir: /config/certs
  cert_file: cert.pem
  key_file: key.pem
  mqtt: {}
schema:
  meters:
    - meter_ip: str
      meter_port: port
  ldfi: str?
  cert_dir: str?
  cert_file: str?
  key_file: str?
  mqtt:
    server: str?
    port: port?
    user: str?
    password: password?
    topic_prefix: str?
